version: '3.2'

services:
  api:
    build: .
    restart: always
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command:
      - sh
      - -c
      - |
        npm install
        npm run typeorm:run
        npm run start:dev
    volumes:
      - .:/app

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: data
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db_data:
